sudo: required

services:
  - docker
  
before_install:
  - docker build -t govkumardocker/docker-app:v4 .
  
script:
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  - docker push govkumardocker/docker-app:v4